"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var PERMISSION;
(function (PERMISSION) {
    PERMISSION["MASTER"] = "master";
    PERMISSION["ADMIN"] = "admin";
})(PERMISSION = exports.PERMISSION || (exports.PERMISSION = {}));
var LOG_TYPE;
(function (LOG_TYPE) {
    LOG_TYPE["RESET_PASSWORD_REQUEST"] = "reset_password_request";
    LOG_TYPE["LOGIN"] = "login";
    LOG_TYPE["LOGIN_FAIL"] = "login_fail";
    LOG_TYPE["REGISTER"] = "register";
})(LOG_TYPE = exports.LOG_TYPE || (exports.LOG_TYPE = {}));
var STATISTICS_RANGE;
(function (STATISTICS_RANGE) {
    STATISTICS_RANGE["YEARLY"] = "yearly";
    STATISTICS_RANGE["WEEKLY"] = "weekly";
})(STATISTICS_RANGE = exports.STATISTICS_RANGE || (exports.STATISTICS_RANGE = {}));
var USER_UPDATE_INFO_ERROR;
(function (USER_UPDATE_INFO_ERROR) {
    USER_UPDATE_INFO_ERROR["EMAIL_EXISTS"] = "email_exists";
    USER_UPDATE_INFO_ERROR["WRONG_PASSWORD"] = "wrong_password";
})(USER_UPDATE_INFO_ERROR = exports.USER_UPDATE_INFO_ERROR || (exports.USER_UPDATE_INFO_ERROR = {}));
var USER_REPORT_STATUS;
(function (USER_REPORT_STATUS) {
    USER_REPORT_STATUS[USER_REPORT_STATUS["ACTIVE"] = 0] = "ACTIVE";
    USER_REPORT_STATUS[USER_REPORT_STATUS["TAKEN"] = 1] = "TAKEN";
    USER_REPORT_STATUS[USER_REPORT_STATUS["CLOSE"] = 2] = "CLOSE";
})(USER_REPORT_STATUS = exports.USER_REPORT_STATUS || (exports.USER_REPORT_STATUS = {}));
var LOCATION_ERROR;
(function (LOCATION_ERROR) {
    LOCATION_ERROR[LOCATION_ERROR["PERMISSION_DENIED"] = 0] = "PERMISSION_DENIED";
    LOCATION_ERROR[LOCATION_ERROR["POSITION_UNAVAILABLE"] = 1] = "POSITION_UNAVAILABLE";
    LOCATION_ERROR[LOCATION_ERROR["TIMEOUT"] = 2] = "TIMEOUT";
    LOCATION_ERROR[LOCATION_ERROR["BROWSER_NOT_SUPPORT"] = 3] = "BROWSER_NOT_SUPPORT";
    LOCATION_ERROR[LOCATION_ERROR["UNKNOWN_ERROR"] = 4] = "UNKNOWN_ERROR";
})(LOCATION_ERROR = exports.LOCATION_ERROR || (exports.LOCATION_ERROR = {}));
//# sourceMappingURL=enums.js.map