export enum PERMISSION {
    MASTER = "MASTER",
    ADMIN = "ADMIN"
}

export enum LOG_TYPE {
    RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST",
    LOGIN = "LOGIN",
    LOGIN_FAIL = "LOGIN_FAIL",
    REGISTER = "REGISTER",
    DELETE_USER = "DELETE_USER"
}

export enum STATISTICS_RANGE {
    YEARLY = "YEARLY",
    WEEKLY = "WEEKLY"
}

export enum USER_UPDATE_INFO_ERROR {
    EMAIL_EXISTS = "EMAIL_EXISTS",
    WRONG_PASSWORD = "WRONG_PASSWORD"
}

export enum SOCKET_STATE {
    ACTIVE = "ACTIVE",
    CLOSE = "CLOSE",
    LOGOUT = "LOGOUT"
}

export enum USER_REPORT_STATUS {
    ACTIVE = "ACTIVE",
    TAKEN = "TAKEN",
    CLOSE = "CLOSE"
}